@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

REM Base drive (E: already named MAIN)
set "BASE=E:\"

REM List of directories to create (relative to %BASE%)
set DIRS=^
  00_INBOX\_TO_PROCESS^
  00_INBOX\_STAGING^
  01_HORIZONS\10_LIFE_AND_LEGACY^
  01_HORIZONS\20_GOALS\_ACTIVE^
  01_HORIZONS\20_GOALS\_ACHIEVED^
  02_PROJECTS\_ACTIVE\COMMISSIONED_[Client]_[Name]\0_Brief_and_Goals^
  02_PROJECTS\_ACTIVE\COMMISSIONED_[Client]_[Name]\1_Research_and_Data^
  02_PROJECTS\_ACTIVE\COMMISSIONED_[Client]_[Name]\2_Work_In_Progress^
  02_PROJECTS\_ACTIVE\COMMISSIONED_[Client]_[Name]\3_Feedback_and_Revisions^
  02_PROJECTS\_ACTIVE\COMMISSIONED_[Client]_[Name]\4_Final_Deliverables^
  02_PROJECTS\_ACTIVE\UNI_[CourseCode]_[ProjectName]^
  02_PROJECTS\_ACTIVE\PERSONAL_[ProjectName]^
  02_PROJECTS\_ARCHIVED^
  03_AREAS\31_PROFESSIONAL\CAREER_DEVELOPMENT^
  03_AREAS\31_PROFESSIONAL\EMPLOYMENT^
  03_AREAS\31_PROFESSIONAL\FINANCES^
  03_AREAS\32_PERSONAL\FINANCES^
  03_AREAS\32_PERSONAL\HEALTH_AND_WELLNESS^
  03_AREAS\32_PERSONAL\HOME_AND_ASSETS^
  03_AREAS\32_PERSONAL\LEGAL_AND_IDENTITY^
  03_AREAS\32_PERSONAL\RELATIONSHIPS^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS101_DataStructures\Lectures^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS101_DataStructures\Readings^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS101_DataStructures\Labs^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS101_DataStructures\Assignments^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS101_DataStructures\Notes^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS202_Algorithms\Lectures^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS202_Algorithms\Readings^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS202_Algorithms\Labs^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS202_Algorithms\Assignments^
  03_AREAS\33_LEARNING_AND_SKILLS\FORMAL_EDUCATION\2024-2025\CS202_Algorithms\Notes^
  03_AREAS\33_LEARNING_AND_SKILLS\UNIVERSITY_RESEARCH^
  03_AREAS\33_LEARNING_AND_SKILLS\SKILL_DEVELOPMENT^
  03_AREAS\33_LEARNING_AND_SKILLS\INTERESTS^
  03_AREAS\34_LEISURE_AND_PASSIONS\HOBBIES^
  03_AREAS\34_LEISURE_AND_PASSIONS\TRAVEL^
  03_AREAS\34_LEISURE_AND_PASSIONS\EVENTS^
  04_RESOURCES\41_KNOWLEDGE_BANK\ARTICLES_AND_PAPERS^
  04_RESOURCES\41_KNOWLEDGE_BANK\BOOKS^
  04_RESOURCES\41_KNOWLEDGE_BANK\COURSES^
  04_RESOURCES\41_KNOWLEDGE_BANK\QUOTES_AND_SNIPPETS^
  04_RESOURCES\41_KNOWLEDGE_BANK\IT_RESEARCH^
  04_RESOURCES\42_MEDIA_LIBRARY\AUDIO^
  04_RESOURCES\42_MEDIA_LIBRARY\DOCUMENTS^
  04_RESOURCES\42_MEDIA_LIBRARY\IMAGES^
  04_RESOURCES\42_MEDIA_LIBRARY\IMAGES\Wallpapers^
  04_RESOURCES\42_MEDIA_LIBRARY\VIDEO^
  04_RESOURCES\42_MEDIA_LIBRARY\FONTS_AND_ICONS^
  04_RESOURCES\43_TEMPLATES_AND_ASSETS\DOCUMENT_TEMPLATES^
  04_RESOURCES\43_TEMPLATES_AND_ASSETS\PRESENTATIONS^
  04_RESOURCES\43_TEMPLATES_AND_ASSETS\SPREADSHEETS^
  04_RESOURCES\43_TEMPLATES_AND_ASSETS\GRAPHIC_ASSETS^
  04_RESOURCES\44_SOFTWARE_AND_CONFIG\APPLICATIONS^
  04_RESOURCES\44_SOFTWARE_AND_CONFIG\CODE_LIBRARY^
  04_RESOURCES\44_SOFTWARE_AND_CONFIG\CONFIG_FILES^
  04_RESOURCES\44_SOFTWARE_AND_CONFIG\VIRTUAL_MACHINES^
  05_OUTPUTS\_DRAFTS_AND_IDEAS^
  05_OUTPUTS\_FINAL^
  09_ARCHIVE\90_VAULT\_IDENTITY_AND_LEGAL^
  09_ARCHIVE\90_VAULT\_FINANCIAL_RECORDS^
  09_ARCHIVE\90_VAULT\_HEALTH_RECORDS^
  09_ARCHIVE\90_VAULT\_PURCHASED_ASSETS^
  09_ARCHIVE\91_PROJECTS_ARCHIVE^
  09_ARCHIVE\92_AREAS_ARCHIVE
)

echo Creating directory structure under %BASE%...
for %%D in (%DIRS%) do (
  md "%BASE%\%%D" 2>nul
  set "README=%BASE%\%%D\README.md"
  if not exist "!README!" (
    echo # %%~nxD>"!README!"
  )
)

REM Create placeholder RULESET.md in the root of E:\
set "RULESET=%BASE%\RULESET.md"
if not exist "%RULESET%" (
  >"%RULESET%" (
    echo # Workspace Ruleset
    echo.
    echo ## 1. File Intake
    echo - All new files land in `00_INBOX\_TO_PROCESS`.
    echo - Move to `_STAGING` once briefly reviewed.
    echo.
    echo ## 2. Project Workflow
    echo - Active projects in `02_PROJECTS\_ACTIVE`; archive when done.
    echo - Use `@` or `zzz_` prefixes for priority ordering.
    echo.
    echo ## 3. Area Management
    echo - Living domains under `03_AREAS`; categorise consistently.
    echo.
    echo ## 4. Resource Library
    echo - Centralise templates, code snippets, and media in `04_RESOURCES`.
    echo.
    echo ## 5. Final Outputs
    echo - Drafts in `05_OUTPUTS\_DRAFTS_AND_IDEAS`; finals in `05_OUTPUTS\_FINAL`.
    echo.
    echo ## 6. Archival
    echo - Immutable records in `09_ARCHIVE\90_VAULT`; general archive by domain/year.
    echo.
    echo *(Fill in and refine these rules to your preference.)*
  )
)

echo.
echo Done. All folders created under %BASE% and RULESET.md generated.
pause
